export default {
  iconList: [
    "account-group",
    "noodles",
    "heart-pulse",
    "book-open-page-variant",
    "gender-male-female",
    "cup-water",
    "lightbulb-on-outline",
    "finance",
    "hammer-screwdriver",
    "equal-box",
    "city",
    "infinity",
    "earth",
    "fishbowl",
    "paw",
    "leaf",
    "google-circles-extended",
  ],
};
