export default {
  titles: [
    "NO POVERTY",
    "ZERO HUNGER",
    "GOOD HEALTH AND WELL-BEING",
    "QUALITY EDUCATION",
    "GENDER EQUALITY",
    "CLEAN WATER AND SANITATION",
    "AFFORDABLE AND CLEAN ENERGY",
    "DECENT WORK AND ECONOMIC GROWTH",
    "INDUSTRY, INNOVATION AND INFRASTRUCTURE",
    "REDUCED INEQUALITIES",
    "SUSTAINABLE CITIES AND COMMUNITIES",
    "RESPONSIBLE CONSUMPTION AND PRODUCTION",
    "CLIMATE ACTION",
    "LIFE BELOW WATER",
    "LIFE ON LAND",
    "PEACE, JUSTICE AND STRONG INSTRUCTIONS",
    "PARTNERSHIPS FOR THE GOALS"
  ],
};
